### ISSUE TITLE
Spit orientation?

### ISSUE THREAD

**Issue by NewAlexandria** [emilsoman/spec-outline.vim#1]
How do we set whether to make a horizontal or vertical split, when opening?

**Comment by emilsoman** [comment]
I haven't added that configuration yet. Till then, you should be able to treat it like any other window, so all window movements should work. For example, to move it to the left, `CTRL-W H` . 

But this is a good feature to have. Where do you prefer the window to be, btw ?

**Comment by NewAlexandria** [comment]
I generally 'dock' things on the right side of the file's split, since the left side often has buffers, nerdtree, etc.  Particularly in this case, a vertical split is important since I have so many lines to read (in the outline) — and I gain nothing by having the split wider (as a horizontal split).  If not on the right vertical side, then I would want it to replace the current split's contents until I press enter or escape

**Comment by emilsoman** [comment]
I agree, keeping the window on the right side makes more sense. Let me look into this.

**Comment by emilsoman** [comment]
Pushed some code to change the default orientation to right side. Also added config to choose one of top, left, bottom or right. See [README](https://github.com/emilsoman/spec-outline.vim#configuration)
