### ISSUE TITLE
Which colorscheme? 

### ISSUE THREAD

**Issue by ReneFroger** [emilsoman/spec-outline.vim#2]
First, I would like to thank you for sharing your work with the Vim community! nfortunately, I'm not programming in Ruby yet (I do PHP, unfortunately), but I wanted to start with that. 

When I noticed your screenshot, I really liked the colors. Which colorscheme was you using in the screenshot? 

Thanks in advance for your reply!

**Comment by ReneFroger** [comment]
Nevermind, the colorscheme seems to be Gvrubox, https://github.com/morhetz/gruvbox

Found it in your dotfiles. Although the colorscheme in your screenshot seems to be more lively.

**Comment by emilsoman** [comment]
You are welcome! spec-outline.vim will work with any spec file which has DSLs starting with `it`, `describe` or `context` . So maybe you can use it with Jasmine if you're using that to test your JS code.

You are right about the color scheme, it's gruvbox.

**Comment by ReneFroger** [comment]
Thanks! Sounds interesting, I will try it. 

Another question yet. I read your blog (well written!), where you wrote that you was gonna make the switch to Sublime Text. But here you made a new plugin. May I assume you're back again to the Vim camp? :P

**Comment by emilsoman** [comment]
Thanks for taking the time to read the blog post. I forced myself to use sublime for a while and not cheat by coming back to vim prematurely, and after I spent enough time, I think sublime's a good editor! I liked many things about sublime like : 
1. It looks beautiful.
2. Has a good centralized plugin repo to search and download plugins from.
3. Snappy fuzzy search.
4. Scrolling through a huge file doesn't hurt the eyes

But I came back to vim, because : 
1. My work is usually entirely in the terminal. I like being able to have an editor wherever I am.
2. I pair-program with my colleagues over the internet often. Can't beat vim + tmux there.
3. Upgrading sublime has bitten me multiple times. ( Screwed up my user preferences for some reason ).
4. Everyday there's something new to learn about Vim. The more you master vim, the more fun it becomes. ( VimGolf is awesome ! )

**Comment by emilsoman** [comment]
By the way, if you're finding trouble with gruvbox colors, maybe [this will help](https://github.com/morhetz/gruvbox/wiki/Terminal-specific).

**Comment by ReneFroger** [comment]
Thanks for your reply. I don't use colorschemes. But I will only use parts of a colorscheme that I like, and add it to my own configured colorscheme. So I saw some nice colors, and I needed the source code to find out which colors for which part was used. May I give you some advice? It seems to me that you didn't know enough plugins for Vims. :P

I will address your point 3 and 4: 

**Point 3: Snappy fuzzy search**. 

I'm not sure what you mean with Fuzzy Search. If you mean grep or something, you can have Ag in your Vim quickfix window: https://github.com/rking/ag.vim 

Or if you mean navigating in code and filebase? Try [Unite](https://github.com/Shougo/unite.vim) with these settings, and don't forget to install [NeoMRU](https://github.com/Shougo/neomru.vim) from Shougo too. 
Then these settings in your .vimrc:  

```
call unite#filters#matcher_default#use(['matcher_fuzzy'])
call unite#filters#sorter_default#use(['sorter_rank'])
call unite#custom#profile('default', 'context', {
\   'start_insert': 1,
\   'winheight': 50,
\   'direction': 'botright',
\   'prompt': '» ',
\ })
call unite#custom#source('file,file/new,file_mru,buffer,file_rec',
\ 'matchers', 'matcher_fuzzy')
let g:unite_data_directory='~/.vim/.cache/unite'
let g:unite_source_history_yank_enable=1
```

And with Ctrl (mine is swapped with Capslock) + L, you open Unite with these setting in vimrc:

```
nnoremap <silent> <C-l> :Unite -auto-resize file file_mru file_rec<cr>
```

Now you have fuzzy search in Vim. If you're editting in a file, and open Unite with C-l You can press esc (Or remap jk <Esc>), to navigate in file base. (The files in same map of the buffer are show first). If you see a folder you want to explore, you type the name of folder. With the file_rec you see the contents of that folder. With file_rec/async, you make it even faster.  :)

For smooth scrolling, [Smooth Scroll from Terryma](https://github.com/terryma/vim-smooth-scroll) is your friend. Personally, I like these settings:

```
nnoremap <CR> :call smooth_scroll#down(&scroll, 25, 3)<cr>
nnoremap <silent> <c-u> :call smooth_scroll#up(&scroll, 12, 3)<cr>
vnoremap <silent> <c-u> :call smooth_scroll#up(&scroll, 12, 3)<cr>
```

But you can modify the speed and behaviour of the scroll with these numbers.  :)

I found it ever better in scrolling than Sublime own smooth scrolling. 

Happy Vimming!

**Comment by emilsoman** [comment]
You need to install a plugin and configure a bunch of things for fuzzy find to work in vim, where as sublime supports really fast fuzzy find with absolutely zero configs. I think it's just a side effect of sublime being a more modern editor, having learned so much from the IDEs out there. I've been using CtrlP for my fuzzy finding for a long time, it works alright. Thanks for suggesting the Unite.vim configs, I'll surely dig deeper next time.

I tried out SmoothScroll, works pretty good for a terminal editor ! Thanks for sharing . What are some of your other favorite plugins ?

**Comment by ReneFroger** [comment]
I used CtrlP long time, and it was one of my favorite plugins. But that's why I especially posted the settings for Unite. With the above settings, Unite will behave like CtrlP, with NERDTree and FuzzyFinder. All together in one plugin, focused to behave like CtrlP. See the link: http://bling.github.io/blog/2013/06/02/unite-dot-vim-the-plugin-you-didnt-know-you-need/ for possibilities. 

I have many plugins. I think it is too much to sum it up. Just give some things that you're missing yet, and I will look if I'm already using a plugin for that.
