### ISSUE TITLE
How to use the `HideFileNameAndLineNo` config?

### ISSUE THREAD

**Issue by NewAlexandria** [emilsoman/spec-outline.vim#3]
Perhaps this is some magic of `conceal`, but I cannot see how to suppress the File Name and Line Number.  Can you advise?

Or, I can pull request for a config that does this; but I suspect that there is a way to enable it.

Thanks

**Comment by NewAlexandria** [comment]
Oh, I see that the file name is an important part of the quickfix list letting `Enter` jump to the selected line.

**Comment by NewAlexandria** [comment]
Can these file and line numbers be moved to the end of the line?  I can't get that to work in my edits

**Comment by emilsoman** [comment]
Are you saying you are able to see the file name and line number in the quickfix window ? Those should be hidden by default . I have this in the plugin : 

``` viml
 " Hide Filename and line no used by quickfix
 syn match HideFileNameAndLineNo "^.*|" conceal
```

^ will create a matching group which will match the filename and line number. Then I say conceal which hides it.

**Comment by NewAlexandria** [comment]
Yes, they appear by default.  Thanks for confirming; after a bit of reading, i grokked that they should be hidden.  What might I look for, to debug this?   [My vimrc](https://github.com/NewAlexandria/vim.ana/blob/master/.vimrc) and other configs are [here](https://github.com/NewAlexandria/vim.ana)

**Comment by emilsoman** [comment]
Can you give me the output of `vim --version` ?

**Comment by NewAlexandria** [comment]
Yes, `+conceal` was a compile option:

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 19 2013 11:09:25)
MacOS X (unix) version
Included patches: 1-52
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +syntax
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
-balloon_eval    +float           +mouse_urxvt     -tag_any_white
-browse          +folding         +mouse_xterm     -tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         -gettext         -mzscheme        +textobjects
-clientserver    -hangul_input    +netbeans_intg   +title
+clipboard       +iconv           +path_extra      -toolbar
+cmdline_compl   +insert_expand   -perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      -lua             +rightleft       +windows
+diff            +menu            +ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      -sniff           -xsmp
+eval            +mouse_dec       +startuptime     -xterm_clipboard
+ex_extra        -mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: /usr/bin/clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X_UNIX  -Os -w -pipe -march=native -mmacosx-version-min=10.8 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      
Linking: /usr/bin/clang   -L.    -L/usr/local/lib -Wl,-headerpad_max_install_names -o vim        -lm  -lncurses -liconv -framework Cocoa    -framework Python   -lruby -lobjc 
```

**Comment by emilsoman** [comment]
Looks fine. Can you try excluding all other plugins and colorschemes and see if it works ?

**Comment by NewAlexandria** [comment]
Nope.  Even without those it still doesn't work.  I also tried removing my `.vim` dir, making a new one, and installing the plugin 'bare' into that fresh directory.  Panel opens, but the text is not concealed.  I had also removed my `.vimrc` and manually added the spec toggle binding via the vim CLI.  Still not concealed.  

I never expected to go this far and still see an issue — but I don't know how conceal works

**Comment by emilsoman** [comment]
Strange that the plugin works for other users. This is going to be tricky.

Can you open a new file in vim and try the following:

```
#Insert the text "hello world" in the buffer , then run these commands
:setlocal conceallevel=3
:setlocal concealcursor=ncv
:syn match HideStuff "lo\sworl" conceal
```

You should see that "hello world" becomes "held".  Can you confirm ?

**Comment by NewAlexandria** [comment]
Does nothing.  and, Only remote machines I can access are compiled without `+conceal`

**Comment by emilsoman** [comment]
If you execute `:echo has('conceal')` , it should give you 1 if conceal is available.
Shouldn't make a difference if you're remotely editing a file or not. The filename and line number can't be hidden if conceal isn't available. :(

**Comment by NewAlexandria** [comment]
`vi` and `vim` were not mapped together on this machine.  Thanks; this explained counter other bugs.

**Comment by NewAlexandria** [comment]
actually, opening on the right side, with conceal, now breaks lines in odd places - like at seemingly-random places in the middle of "describe".  Lines not split are still 'doubled' by adding a blank line - like double-spacing.  These are all one 'line' in terms of pressing enter and jumping to that line.  But after all the time spent on this other matter, I can't bog us down further with more things.  FYI.

**Comment by NewAlexandria** [comment]
Thank you for your help

**Comment by emilsoman** [comment]
Can you give me a screenshot please ?

**Comment by NewAlexandria** [comment]
well, sorry, but I already uninstalled.  I found that Unit-Outline had a different mode that I could use to launch it; and it's a bit better because
- it colorizes and indents
- it narrows the list based on typing in Insert mode (because of Unite)

This looks great for people who are not on Unite, though

**Comment by emilsoman** [comment]
Cool, no issues. By the way, spec-outline.vim also indents and colorizes! No fuzzy find, though, because the idea is that this plugin will be more useful when navigating a codebase you are not familiar with, hence motion commands will be more apt than fuzzy find. Thanks for trying it out, anyways !
